name: Deploy Website to Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH key for authentication
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/duwin.pem
          chmod 600 ~/.ssh/duwin.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 3: SSH into the server and execute the deployment commands
      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/duwin.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

            # Setup repository details
            REPO_NAME=${{ github.repository }}
            REPO_NAME=${REPO_NAME//\//_} # Replace "/" in repo name

            # Create the project directory if it doesn't exist
            if [ ! -d "/var/www/$REPO_NAME" ]; then
              echo "Creating directory /var/www/$REPO_NAME..."
              sudo mkdir -p /var/www/$REPO_NAME
              sudo chown $USER:$USER /var/www/$REPO_NAME
            fi

            # Navigate to the project directory
            cd /var/www/$REPO_NAME

            # Clone or pull the repository
            if [ ! -d ".git" ]; then
              echo "Cloning repository..."
              git clone https://github.com/${{ github.repository }} .
            else
              echo "Pulling latest changes..."
              git pull origin main
            fi

            # Install dependencies if package.json exists
            if [ -f "package.json" ]; then
              echo "Installing dependencies..."
              npm install
            else
              echo "No package.json found, skipping dependency installation."
            fi

            # Start or restart the application using PM2
            if pm2 list | grep -q "$REPO_NAME"; then
              echo "Restarting PM2 process..."
              pm2 restart "$REPO_NAME"
            else
              echo "Starting PM2 process..."
              pm2 start npm --name "$REPO_NAME" -- start
              pm2 save  # Save PM2 configuration to restart on reboot
            fi

          EOF

      # Step 4: Clean up SSH key
      - name: Clean up SSH key
        run: rm -f ~/.ssh/duwin.pem
